
#include <stdint.h>
#include "weights.h"  // Pulls in the L1_MULT macro generated by Python

#ifdef __GNUC__
    #define HW_DELAY_NOPS() __asm__ volatile("nop\n\tnop\n\tnop\n\tnop\n\tnop")
#else
    #define HW_DELAY_NOPS()
#endif

// --- Coprocessor MMIO Map ---
#define COP_BASE       0xC0000000
volatile uint32_t* COP_START      = (uint32_t*)(COP_BASE + 0x00);
volatile uint32_t* COP_STATUS     = (uint32_t*)(COP_BASE + 0x04);
volatile uint32_t* COP_IN_BASE    = (uint32_t*)(COP_BASE + 0x08);
volatile uint32_t* COP_WT_BASE    = (uint32_t*)(COP_BASE + 0x0C);
volatile uint32_t* COP_OUT_BASE   = (uint32_t*)(COP_BASE + 0x10);
volatile uint32_t* COP_LAYER_ROWS = (uint32_t*)(COP_BASE + 0x14);
volatile uint32_t* COP_LAYER_COLS = (uint32_t*)(COP_BASE + 0x18);
volatile uint32_t* COP_BIAS_BASE  = (uint32_t*)(COP_BASE + 0x1C);
volatile uint32_t* COP_CYCLE_CNT  = (uint32_t*)(COP_BASE + 0x20);
volatile uint32_t* COP_RELU_EN    = (uint32_t*)(COP_BASE + 0x24);
volatile uint32_t* COP_IMG_READY  = (uint32_t*)(COP_BASE + 0x28);
volatile uint32_t* COP_CAPTURE_EN  = (uint32_t*)(COP_BASE + 0x2C);

// --- BRAM Pointers ---
volatile uint32_t* WEIGHT_BRAM = (uint32_t*)(0xC0010000);
volatile uint32_t* INPUT_BRAM  = (uint32_t*)(0xC0020000);
volatile int32_t* OUTPUT_BRAM = (int32_t*) (0xC0030000);
volatile int32_t* BIAS_BRAM   = (int32_t*) (0xC0040000);

#define INPUT_DIM  784
#define L1_NEURONS 128
#define L2_NEURONS 10

#define WAIT_DONE() do {                         \
    HW_DELAY_NOPS();                             \
    while ((*COP_STATUS & 0x01) != 0);           \
} while(0)

int main() {
    while (1) {
        // -----------------------------------------------------------------
        // STEP 0: Wait for image from UART
        // -----------------------------------------------------------------
        while ((*COP_IMG_READY & 0x01) == 0);

        *COP_IMG_READY = 0;

        // -----------------------------------------------------------------
        // STEP 1: Layer 1  (784 inputs -> 128 hidden neurons, WITH ReLU)
        // -----------------------------------------------------------------
        *COP_CAPTURE_EN = 0; // Don't show hidden neurons on 7-seg
        *COP_RELU_EN    = 1;
        *COP_IN_BASE    = 0;
        *COP_WT_BASE    = 0;
        *COP_OUT_BASE   = 0;
        *COP_BIAS_BASE  = 0;
        *COP_LAYER_ROWS = L1_NEURONS;
        *COP_LAYER_COLS = INPUT_DIM;

        // Pulse the start flag safely
        *COP_START = 1;
        *COP_START = 0;
        WAIT_DONE();

        // -----------------------------------------------------------------
        // STEP 2: EXACT Re-Quantisation (INT32 -> INT8)
        // Optimized for speed: L1_MULT is 473. 
        // 473 = 256 + 128 + 64 + 16 + 8 + 1
        // -----------------------------------------------------------------
        for (int i = 0; i < (L1_NEURONS / 4); i++) {
            uint32_t packed = 0;
            for (int j = 0; j < 4; j++) {
                int32_t val = OUTPUT_BRAM[i * 4 + j];
                
                // Fast Fixed Point math for L1_MULT=473 with 64-bit intermediate
                // to prevent overflow (12M * 473 = 5.6B > 2^31)
                int64_t val64 = (int64_t)val;
                int64_t prod = (val64 << 8) + (val64 << 7) + (val64 << 6) + (val64 << 4) + (val64 << 3) + val64;
                val = (int32_t)(prod >> 16);

                // ReLU enforces 0 minimum. 127 is max INT8 positive.
                if (val > 127) val = 127;
                if (val < 0)   val = 0;

                packed |= ((val & 0xFF) << (j * 8));
            }
            INPUT_BRAM[i] = packed;
        }

        // -----------------------------------------------------------------
        // STEP 3: Layer 2  (128 hidden -> 10 output classes, NO ReLU)
        // -----------------------------------------------------------------
        *COP_CAPTURE_EN = 1; // Enable logit capture for class scores
        *COP_RELU_EN    = 0; // Raw logits needed for correct argmax

        int L2_WT_OFFSET   = (INPUT_DIM * L1_NEURONS) / 4;
        int L2_BIAS_OFFSET = L1_NEURONS;

        *COP_IN_BASE    = 0;
        *COP_WT_BASE    = L2_WT_OFFSET;
        *COP_OUT_BASE   = 0;
        *COP_BIAS_BASE  = L2_BIAS_OFFSET;
        *COP_LAYER_ROWS = L2_NEURONS;
        *COP_LAYER_COLS = L1_NEURONS;

        // Pulse the start flag safely
        *COP_START = 1;
        *COP_START = 0;
        WAIT_DONE();
    }

    return 0;
}
